accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('project/new/', views.ProjectCreateView.as_view(), name='project-create'),
    path('project/<pk>/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('project/<pk>/update/', views.ProjectUpdateView.as_view(), name='project-update'),
    path('project/<pk>/delete/', views.ProjectDeleteView.as_view(), name="project-delete"),
    path('contractor/new/', views.ContractorCreateView.as_view(), name='contractor-create'),
    path('contractor/<pk>/', views.ContractorDetailView.as_view(), name='contractor-detail'),
    path('contractor/<pk>/update/', views.ContractorUpdateView.as_view(), name='contractor-update'),
    path('contractor/<pk>/delete/', views.ContractorDeleteView.as_view(), name='contractor-delete'),
]

documentation_practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project-detail', kwargs={'pk': self.pk})


class Contractor(models.Model):
    name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.name + " " + self.last_name

    def get_absolute_url(self):
        return reverse('contractor-detail', kwargs={'pk': self.pk})

accounts/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Project, Contractor
from django.urls import reverse_lazy

'''Project classes'''


class Index(ListView):
    model = Project


class ProjectDetailView(DetailView):
    model = Project


class ProjectCreateView(CreateView):
    model = Project
    fields = ['name', 'description']


class ProjectUpdateView(UpdateView):
    model = Project
    fields = ['name', 'description']
    template_name_suffix = '_update_form'


class ProjectDeleteView(DeleteView):
    model = Project
    template_name = 'accounts/project_delete.html'
    success_url = "/"


'''Contractor related classes'''


class ContractorCreateView(CreateView):
    model = Contractor
    fields = ['name', 'last_name', 'email', 'project']


class ContractorDetailView(DetailView):
    model = Contractor


class ContractorUpdateView(UpdateView):
    model = Contractor
    template_name = 'accounts/contractor_update.html'
    fields = ['name', 'last_name', 'email', 'project']


class ContractorDeleteView(DeleteView):
    model = Contractor
    template_name = 'accounts/contractor_delete.html'
    success_url = "/"

templates/accounts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"></script>
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Dev.Pro</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project-create' %}">New Project</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contractor-create' %}">New Contractor</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

templates/accounts/contractor_delete.html
{% extends 'accounts/base.html' %}
{% block body_block %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

templates/accounts/contractor_detail.html
{% extends 'accounts/base.html' %}
{% block body_block %}
    {% if contractor %}
        <h1>{{ contractor.name }} {{ contractor.last_name }}</h1>
        <p>{{ contractor.email }}</p>
        <p>{{ contractor.project }}</p>
    {% else %}
        <p>There's no such contractor</p>
    {% endif %}
    <a href="{% url 'contractor-update' contractor.pk %}">Update contractor's info</a>
    <a href="{% url 'contractor-delete' contractor.pk %}">Delete contractor</a>
{% endblock %}

templates/accounts/contractor_form.html
{% extends 'accounts/base.html' %}
{% block body_block %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock %}

templates/accounts/contractor_update.html
{% extends 'accounts/base.html' %}
{% block body_block %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

templates/accounts/project_delete.html
{% extends 'accounts/base.html' %}
{% block body_block %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

templates/accounts/project_detail.html
{% extends 'accounts/base.html' %}
{% block body_block %}
    <h1>{{ project.name }}</h1>
    <p>Description:<br>{{ project.description }}</p>

    <p>Contractors:<br>
        {% if project.contractor_set.all %}

            {% for x in project.contractor_set.all %}
                <a href="{{ x.get_absolute_url }}">{{ x }}</a><br>
            {% endfor %}

        {% else %}
            <p>This project has no contractors yet</p>

        {% endif %}
    </p>
    <a href="{% url 'project-update' project.pk %}">Update project</a>
    <a href="{% url 'project-delete' project.pk %}">Delete project</a>
{% endblock %}

templates/accounts/project_form.html
{% extends 'accounts/base.html' %}
{% block body_block %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock %}

templates/accounts/project_list.html
{% extends 'accounts/base.html' %}
{% block body_block %}
    <h1>This is a home page. List of all projects</h1>
    {% for proj in project_list %}
        <ul>
            <lable><a href="{{ proj.get_absolute_url }}">{{ proj.name }}</a>:</lable>
            <li>Description: {{ proj.description }}</li><br>
            <p>Contractors:<br>
            {% if proj.contractor_set.all %}

                {% for x in proj.contractor_set.all %}
                    <a href="{{ x.get_absolute_url }}">{{ x }}</a><br>
                {% endfor %}

            {% else %}
                <p>This project has no contractors yet</p>

            {% endif %}
            </p>
        </ul><br>
    {% endfor %}
{% endblock %}

templates/accounts/project_update_form.html
{% extends 'accounts/base.html' %}
{% block body_block %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}